### ISSUE TITLE
运行出错不知道哪里没弄好

### ISSUE THREAD

**Issue by 80000v** [hojas/kblog#1]
root@localhost:~/kblog# pm2 show <0|kblog>
-bash: syntax error near unexpected token `newline'
root@localhost:~/kblog# pm2 show 0|kblog
No command 'kblog' found, did you mean:
 Command 'klog' from package 'klog' (universe)
 Command 'klog' from package 'openafs-krb5' (universe)
 Command 'klog' from package 'openafs-client' (universe)
kblog: command not found
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)
root@localhost:~/kblog# pm2 show 0|kblog
No command 'kblog' found, did you mean:
 Command 'klog' from package 'openafs-client' (universe)
 Command 'klog' from package 'openafs-krb5' (universe)
 Command 'klog' from package 'klog' (universe)
kblog: command not found
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at WriteWrap.afterWrite (net.js:763:14)

**Comment by hojas** [comment]
使用命令 `pm2 show 0`（0是启动的app的ID） 或者 `pm2 show kblog`（kblog是启动的app的名称） 查看是否启动成功，而不是 `pm2 show 0|kblog` 。或者可以用 `pm2 list` 命令查看启动的所有app。
