### ISSUE TITLE
nginx 反向代理后出现session失效，如何解决？

### ISSUE THREAD

**Issue by yaotaiye** [hojas/kblog#2]
我用Nginx从域名www.zgniao.wang:80 
代理到我的服务器7001端口http://39.108.99.10:7001/ 
访问我的node服务，这时候用了域名跳过来，登录的时候session失效了，如果直接用IP访问登录的session就没问题。

**Comment by hojas** [comment]
启动服务的IP设置为 '0.0.0.0' 试试
